name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  backend:
    name: Build Backend
    uses: ./.github/workflows/build-image.yml
    with:
      context: backend
    secrets: inherit

  frontend:
    name: Build Frontend
    uses: ./.github/workflows/build-image.yml
    with:
      context: frontend
    secrets: inherit

