name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow for frontend
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'build-image.yml'
          ref: ${{ github.ref }}
          inputs: |
            context: frontend

      - name: Call workflow for backend
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'build-image.yml'
          ref: ${{ github.ref }}
          inputs: |
            context: backend
